apiVersion: v1
kind: ReplicaSet
metadata:
  name: replicaset 
  labels:
    purpose: replicaset-demo
spec:
 replicas: 3
 selector:
   matchLabels:
     project: roboshop
     env: dev
 template:
   metadata:
    project: roboshop
    env: dev
 spec:
  containers:
    - name: nginx
      image: nginx

